# -*- coding: utf-8 -*-
"""export_mlp_c.py — 把 model_mlp.pt + norm_mlp.npz 导出为 C 头文件 mlp_weights.h

用法:  cd ml && python export_mlp_c.py
生成:  ../sdk/student_template/mlp_weights.h (自动生成, 勿手改)

结构: backbone 3 层 Linear+ReLU, head_t 线性头 + sigmoid (仅主头, 辅头不导出)
"""
from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import torch

from train_mlp import MODEL_PATH, NORM_PATH

OUT_PATH = Path(__file__).resolve().parent.parent / "sdk" / "student_template" / "mlp_weights.h"


def fmt_array(name: str, a: np.ndarray) -> str:
    v = np.asarray(a, dtype=np.float32).ravel()
    body = ",\n    ".join(",".join(f"{x:.9g}" for x in v[i:i + 10])
                           for i in range(0, v.size, 10))
    return f"static const float {name}[{v.size}] = {{\n    {body},\n}};\n"


def main() -> None:
    ckpt = torch.load(MODEL_PATH, map_location="cpu", weights_only=True)
    sd = ckpt["state_dict"]
    norm = np.load(NORM_PATH)
    mu, sdv = norm["mu"], norm["sd"]
    in_dim = int(ckpt["in_dim"])
    assert mu.shape[0] == in_dim, "特征维度与归一化参数不一致"

    # backbone Linear 层按顺序号排列 (Sequential 中 Linear/ReLU 交替)
    ids = sorted({int(m.group(1)) for k in sd
                  if (m := re.match(r"backbone\.(\d+)\.weight$", k))})
    layers = []
    for i in ids:
        layers.append((sd[f"backbone.{i}.weight"].numpy(),      # (out, in)
                       sd[f"backbone.{i}.bias"].numpy()))
    layers.append((sd["head_t.weight"].numpy(), sd["head_t.bias"].numpy()))
    n = len(layers)
    max_w = max(max(w.shape) for w, _ in layers)

    out = [
        "/* mlp_weights.h - Auto-generated by ml/export_mlp_c.py, do not edit. */",
        "/* MLP: t_start/total_time predictor (safe oracle, 100k dataset).    */",
        "#ifndef MLP_WEIGHTS_H",
        "#define MLP_WEIGHTS_H",
        "",
        f"#define MLP_IN_DIM {in_dim}",
        f"#define MLP_N_LAYERS {n}",
        f"#define MLP_MAX_WIDTH {max_w}",
        "",
        f"static const int MLP_LAYER_IN[{n}] = {{{', '.join(str(w.shape[1]) for w, _ in layers)}}};",
        f"static const int MLP_LAYER_OUT[{n}] = {{{', '.join(str(w.shape[0]) for w, _ in layers)}}};",
        "",
    ]
    for idx, (w, b) in enumerate(layers):
        out.append(fmt_array(f"mlp_w{idx}", w))
        out.append(fmt_array(f"mlp_b{idx}", b))
    out.append(fmt_array("mlp_mu", mu))
    out.append(fmt_array("mlp_sd", sdv))
    out.append("static const float *const MLP_W[MLP_N_LAYERS] = "
               "{" + ", ".join(f"mlp_w{i}" for i in range(n)) + "};")
    out.append("static const float *const MLP_B[MLP_N_LAYERS] = "
               "{" + ", ".join(f"mlp_b{i}" for i in range(n)) + "};")
    out.append("")
    out.append("#endif /* MLP_WEIGHTS_H */")

    OUT_PATH.write_text("\n".join(out), encoding="ascii")
    shapes = " -> ".join(f"{w.shape[1]}x{w.shape[0]}" for w, _ in layers)
    n_par = sum(w.size + b.size for w, b in layers)
    print(f"written {OUT_PATH}")
    print(f"layers: {shapes}  params: {n_par}  (float32)")


if __name__ == "__main__":
    main()
